### ISSUE TITLE
PHP Fatal Error after updating to Version 2.5.4/2.5.5 - Blacklist is already an array

### ISSUE THREAD

**Issue by natewitty** [crosspeaksoftware/gravity-forms-email-blacklist#37]
After updating this plugin earlier this month to 2.5.4/2.5.5, we started encountering a PHP Fatal Error:

`PHP Fatal error: Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in /wp-content/plugins/gravity-forms-email-blacklist/includes/class-gfemailblacklist.php:259`

This line of code is expecting a string, but is getting an array: 
`$blacklist = explode( ',', $blacklist );` 

As a workaround, I changed that line to: 
`if( !is_array( $blacklist ) ) { $blacklist = explode( ',', $blacklist );}`

This seems to work for now, but I wanted to mention it here so things could be fixed in a future update. 

Thank you.

**Comment by matt-h** [comment]
Fixed in 74d21309ee82563888fd13e137a3e56a50ab6d8b

Released in [2.5.6](https://github.com/crosspeaksoftware/gravity-forms-email-blacklist/releases/tag/2.5.6)
